// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyC1mgLBxZIb0IKdE19XEPbLyaV65cz_pz0',
    appId: '1:385197141284:web:c5e779e79f1ee54451d7b1',
    messagingSenderId: '385197141284',
    projectId: 'groupie-822ab',
    authDomain: 'groupie-822ab.firebaseapp.com',
    storageBucket: 'groupie-822ab.appspot.com',
    measurementId: 'G-GC98XBZKXV',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAdyhvFKdmFv0kcoSP-a_bxKzYzJL5wYLM',
    appId: '1:385197141284:android:ebe39fa55c23d79d51d7b1',
    messagingSenderId: '385197141284',
    projectId: 'groupie-822ab',
    storageBucket: 'groupie-822ab.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDVXz9u3ATY0Bwjy6Qypo8hi_p5EGr3z-M',
    appId: '1:385197141284:ios:946ed4f879ee939151d7b1',
    messagingSenderId: '385197141284',
    projectId: 'groupie-822ab',
    storageBucket: 'groupie-822ab.appspot.com',
    iosBundleId: 'com.example.flutterApplication1',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDVXz9u3ATY0Bwjy6Qypo8hi_p5EGr3z-M',
    appId: '1:385197141284:ios:946ed4f879ee939151d7b1',
    messagingSenderId: '385197141284',
    projectId: 'groupie-822ab',
    storageBucket: 'groupie-822ab.appspot.com',
    iosBundleId: 'com.example.flutterApplication1',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyC1mgLBxZIb0IKdE19XEPbLyaV65cz_pz0',
    appId: '1:385197141284:web:ac667e2afee4351e51d7b1',
    messagingSenderId: '385197141284',
    projectId: 'groupie-822ab',
    authDomain: 'groupie-822ab.firebaseapp.com',
    storageBucket: 'groupie-822ab.appspot.com',
    measurementId: 'G-TPB4XFD6VB',
  );
}
